import React,{useEffect,useMemo,useState} from 'react';
import {Bell,CheckCircle2,Mail,Package,Phone,RefreshCw,Search,Users,Coins,Plus} from 'lucide-react';
import {supabase} from '../../lib/supabase';
import Button from '../ui/Button';

const config={
 users:{title:'Users',eyebrow:'ADMIN',icon:Users,query:async()=>supabase.from('profiles').select('id,display_name,phone,is_tenant,is_owner,is_shop,is_admin,created_at').order('created_at',{ascending:false}).limit(200),map:r=>({id:r.id,title:r.display_name||'RoomOra user',meta:[r.is_admin?'Admin':r.is_owner?'Owner':r.is_shop?'Shop':'Tenant',r.phone].filter(Boolean).join(' · '),date:r.created_at})},
 products:{title:'Products',eyebrow:'MY PRODUCTS',icon:Package,query:(user)=>supabase.from('marketplace_items').select('*').eq('user_id',user.id).neq('category','room').order('created_at',{ascending:false}).limit(100),map:r=>({id:r.id,title:r.title,meta:`${r.locality}, ${r.city} · ${r.status}`,date:r.created_at,price:r.price})},
 inquiries:{title:'Inquiries',eyebrow:'CUSTOMER MESSAGES',icon:Mail,query:(user)=>supabase.from('marketplace_inquiries').select('*,marketplace_items(title,city,locality)').eq('publisher_id',user.id).order('created_at',{ascending:false}).limit(100),map:r=>({id:r.id,title:r.marketplace_items?.title||'Marketplace inquiry',meta:`${r.status||'pending'} · ${r.message||''}`,date:r.created_at,status:r.status})},
 contacts:{title:'Contacts',eyebrow:'UNLOCKED CONTACTS',icon:Phone,query:(user)=>supabase.from('owner_contact_unlocks').select('*,rooms(title,city,locality)').eq('requester_id',user.id).order('created_at',{ascending:false}).limit(100),map:r=>({id:r.id,title:r.rooms?.title||'Room contact',meta:`${r.rooms?.locality||''}, ${r.rooms?.city||''} · ${r.token_cost||0} tokens`,date:r.created_at})},
 orders:{title:'Orders',eyebrow:'SHOP REQUESTS',icon:Package,query:(user)=>supabase.from('marketplace_inquiries').select('*,marketplace_items(title,price,city,locality)').eq('publisher_id',user.id).order('created_at',{ascending:false}).limit(100),map:r=>({id:r.id,title:r.marketplace_items?.title||'Item request',meta:`${r.status||'pending'} · ₹${Number(r.marketplace_items?.price||0).toLocaleString('en-IN')}`,date:r.created_at,status:r.status})}
};

export default function DashboardWorkspacePanel({kind,user,admin=false}){
 const c=config[kind]||config.products; const Icon=c.icon; const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[busy,setBusy]=useState(''),[grant,setGrant]=useState({});
 const load=async()=>{setLoading(true);setError('');const result=await c.query(user);if(result.error)setError(result.error.message);setRows(result.data||[]);setLoading(false)};
 useEffect(()=>{if(user?.id)load()},[user?.id,kind]);
 const items=useMemo(()=>rows.map(c.map).filter(x=>`${x.title} ${x.meta}`.toLowerCase().includes(query.trim().toLowerCase())),[rows,query]);
 const updateInquiry=async(row,status)=>{setBusy(row.id);const {error:e}=await supabase.from('marketplace_inquiries').update({status,updated_at:new Date().toISOString()}).eq('id',row.id).eq('publisher_id',user.id);if(e)setError(e.message);else setRows(v=>v.map(x=>x.id===row.id?{...x,status}:x));setBusy('')};
 const grantTokens=async(id)=>{const amount=Math.floor(Number(grant[id]));if(!Number.isFinite(amount)||amount<1){setError('Enter a positive token amount.');return}setBusy(`grant:${id}`);setError('');const {error:e}=await supabase.rpc('admin_grant_tokens',{p_user_id:id,p_amount:amount,p_description:`Admin token grant: +${amount} tokens`});if(e)setError(e.message);else setGrant(v=>({...v,[id]:''}));setBusy('')};
 return <section className="dash-panel dash-reveal"><div className="dash-panel-head"><div><span>{c.eyebrow}</span><h3>{c.title}</h3></div><div className="workspace-head-actions"><Button variant="secondary" size="sm" onClick={load} disabled={loading}><RefreshCw size={14}/> Refresh</Button><Icon size={18}/></div></div><div className="workspace-toolbar"><div className="workspace-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${c.title.toLowerCase()}…`}/></div><span>{items.length} result{items.length===1?'':'s'}</span></div>{error&&<div className="auth-message" role="alert">{error}</div>}{loading?<div className="dash-empty">Loading {c.title.toLowerCase()}…</div>:items.length?<div className="workspace-list">{items.map(item=><article className="workspace-item" key={item.id}><div className="row-icon"><Icon size={16}/></div><div className="workspace-item-main"><b>{item.title}</b><span>{item.meta}</span><small>{item.date?new Date(item.date).toLocaleDateString('en-IN'):''}</small></div>{kind==='users'&&admin&&<div className="workspace-token-grant"><Coins size={14}/><input type="number" min="1" max="1000000" value={grant[item.id]||''} onChange={e=>setGrant(v=>({...v,[item.id]:e.target.value}))} placeholder="Tokens" aria-label={`Tokens to grant to ${item.title}`}/><Button size="sm" variant="primary" disabled={busy===`grant:${item.id}`} onClick={()=>grantTokens(item.id)}><Plus size={13}/> Give</Button></div>}{item.price!==undefined&&<strong>₹{Number(item.price||0).toLocaleString('en-IN')}</strong>}{(kind==='inquiries'||kind==='orders')&&<div className="workspace-actions">{item.status!=='accepted'&&<Button size="sm" variant="primary" disabled={busy===item.id} onClick={()=>updateInquiry(rows.find(r=>r.id===item.id),'accepted')}><CheckCircle2 size={14}/> Accept</Button>}{item.status!=='declined'&&<Button size="sm" variant="danger" disabled={busy===item.id} onClick={()=>updateInquiry(rows.find(r=>r.id===item.id),'declined')}>Decline</Button>}</div>}</article>)}</div>:<div className="dash-empty"><div className="dash-empty-icon"><Icon size={20}/></div><b>{query?'No matching records':`No ${c.title.toLowerCase()} yet`}</b><span>{query?'Try a different search.':'New activity will appear here automatically.'}</span></div>}</section>
}
