import React,{useState} from 'react';
import {Home,X,Upload} from 'lucide-react';
import {supabase} from './lib/supabase';
const initial={title:'',address:'',locality:'',city:'Lucknow',price:'',facilities:'',images:[]};
export default function AddRoomPanel({user,onCreated}){
 const [open,setOpen]=useState(false),[form,setForm]=useState(initial),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const change=e=>setForm(f=>({...f,[e.target.name]:e.target.value}));
 const pick=e=>{const imgs=Array.from(e.target.files||[]).slice(0,3);setForm(f=>({...f,images:imgs}));setMessage(e.target.files?.length>3?'Only the first 3 images can be selected.':'')};
 const remove=i=>setForm(f=>({...f,images:f.images.filter((_,n)=>n!==i)}));
 const submit=async e=>{e.preventDefault();setMessage('');if(!user?.id)return;if(form.images.length<1){setMessage('Please upload at least 1 room image.');return}setBusy(true);try{const urls=[];for(const image of form.images){const ext=image.name.split('.').pop().toLowerCase();const path=`${user.id}/rooms/${crypto.randomUUID()}.${ext}`;const upload=await supabase.storage.from('marketplace-images').upload(path,image,{upsert:false,contentType:image.type});if(upload.error)throw upload.error;urls.push(supabase.storage.from('marketplace-images').getPublicUrl(path).data.publicUrl)}const {error}=await supabase.from('rooms').insert({owner_id:user.id,title:form.title.trim(),address:form.address.trim(),locality:form.locality.trim(),city:form.city.trim(),monthly_price:Number(form.price),facilities:form.facilities.split(',').map(x=>x.trim()).filter(Boolean),status:'published',image_url:urls[0],image_urls:urls});if(error)throw error;setForm(initial);setOpen(false);onCreated?.()}catch(e){setMessage(e.message||'Unable to publish room.')}finally{setBusy(false)}};
 return <><button className="dash-primary" onClick={()=>setOpen(true)}><Home size={16}/> Add room</button>{open&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><section className="auth-modal"><button className="modal-close" onClick={()=>setOpen(false)}><X size={18}/></button><div className="eyebrow"><Home size={14}/> ROOM LISTING</div><h2>Add a room.</h2><p className="modal-copy">Add 1 to 3 room images. Your first image becomes the cover.</p><form onSubmit={submit}><label className="form-label">Room images <span>*</span><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={pick} required/><small>Choose 1 to 3 JPG, PNG or WebP images.</small></label>{form.images.length>0&&<div className="upload-previews">{form.images.map((img,i)=><div className="upload-preview" key={`${img.name}-${i}`}><img src={URL.createObjectURL(img)} alt={`Room image ${i+1}`}/><button type="button" onClick={()=>remove(i)}><X size={14}/></button><span>{i===0?'Cover':i+1}</span></div>)}</div>}<label className="form-label">Title<input name="title" value={form.title} onChange={change} placeholder="Furnished room near campus" required/></label><label className="form-label">Address<input name="address" value={form.address} onChange={change} placeholder="Building / street" required/></label><div className="role-grid"><label className="form-label">Locality<input name="locality" value={form.locality} onChange={change} placeholder="Gomti Nagar" required/></label><label className="form-label">City<input name="city" value={form.city} onChange={change} required/></label></div><label className="form-label">Monthly rent (₹)<input name="price" type="number" min="1" value={form.price} onChange={change} placeholder="8500" required/></label><label className="form-label">Facilities<input name="facilities" value={form.facilities} onChange={change} placeholder="Wi-Fi, Furnished, Parking"/></label>{message&&<div className="auth-message">{message}</div>}<button className="auth-submit" disabled={busy}>{busy?'Publishing…':'Publish room'}</button></form></section></div>}</>;
}
