import React, { useState } from 'react';
import { Home, X } from 'lucide-react';
import { supabase } from './lib/supabase';

export default function AddRoomPanel({ user, onCreated }) {
  const [open,setOpen]=useState(false); const [form,setForm]=useState({title:'',address:'',locality:'',city:'Lucknow',price:'',facilities:''}); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
  const change=e=>setForm(f=>({...f,[e.target.name]:e.target.value}));
  const submit=async e=>{e.preventDefault();setMessage('');if(!user?.id)return;setBusy(true);const {error}=await supabase.from('rooms').insert({owner_id:user.id,title:form.title.trim(),address:form.address.trim(),locality:form.locality.trim(),city:form.city.trim(),monthly_price:Number(form.price),facilities:form.facilities.split(',').map(x=>x.trim()).filter(Boolean),status:'published'});if(error)setMessage(error.message);else{setForm({title:'',address:'',locality:'',city:'Lucknow',price:'',facilities:''});setOpen(false);onCreated?.()}setBusy(false)};
  return <><button className="dash-primary" onClick={()=>setOpen(true)}><Home size={16}/> Add room</button>{open&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><section className="auth-modal" role="dialog" aria-modal="true"><button className="modal-close" onClick={()=>setOpen(false)}><X size={18}/></button><div className="eyebrow"><Home size={14}/> ROOM LISTING</div><h2>Add a room.</h2><p className="modal-copy">Publish your room first, then you can advertise it using 5 tokens for one month.</p><form onSubmit={submit}><label className="form-label">Title<input name="title" value={form.title} onChange={change} placeholder="Furnished room near campus" required/></label><label className="form-label">Address<input name="address" value={form.address} onChange={change} placeholder="Building / street" required/></label><div className="role-grid"><label className="form-label">Locality<input name="locality" value={form.locality} onChange={change} placeholder="Gomti Nagar" required/></label><label className="form-label">City<input name="city" value={form.city} onChange={change} required/></label></div><label className="form-label">Monthly rent (₹)<input name="price" type="number" min="1" value={form.price} onChange={change} placeholder="8500" required/></label><label className="form-label">Facilities<input name="facilities" value={form.facilities} onChange={change} placeholder="Wi-Fi, Furnished, Parking"/></label>{message&&<div className="auth-message">{message}</div>}<button className="auth-submit" disabled={busy}>{busy?'Publishing…':'Publish room'}</button></form></section></div>}</>;
}
