import React,{useEffect,useMemo,useState} from 'react';
import {BarChart3,CalendarDays,Receipt,Users,Wallet} from 'lucide-react';
import {supabase} from './lib/supabase';

const monthLabels=Array.from({length:6},(_,i)=>{const d=new Date();d.setMonth(d.getMonth()-5+i,1);return d.toLocaleString('en-IN',{month:'short'});});
export default function AdminAnalytics({historyOnly=false}){
 const [subs,setSubs]=useState([]),[users,setUsers]=useState([]),[loading,setLoading]=useState(true);
 useEffect(()=>{let alive=true;(async()=>{setLoading(true);const [s,u]=await Promise.all([supabase.from('user_subscriptions').select('*,subscription_plans(name,monthly_price)').order('created_at',{ascending:false}).limit(500),supabase.from('profiles').select('id,created_at')]);if(alive){setSubs(s.data||[]);setUsers(u.data||[]);setLoading(false)}})();return()=>{alive=false}},[]);
 const monthly=useMemo(()=>monthLabels.map((label,i)=>{const now=new Date();const start=new Date(now.getFullYear(),now.getMonth()-5+i,1);const end=new Date(now.getFullYear(),now.getMonth()-4+i,1);const rows=subs.filter(s=>new Date(s.created_at)>=start&&new Date(s.created_at)<end);return {label,count:rows.length,revenue:rows.reduce((a,s)=>a+Number(s.subscription_plans?.monthly_price||0),0)}}),[subs]);
 const max=Math.max(1,...monthly.map(x=>x.count)); const active=subs.filter(s=>s.status==='active').length; const revenue=monthly.reduce((a,x)=>a+x.revenue,0);
 if(loading)return <div className="dash-empty">Loading admin data…</div>;
 if(historyOnly)return <section className="admin-history"><div className="dash-stats"><div className="dash-stat"><div className="dash-stat-icon"><Receipt size={18}/></div><div><span>Total subscriptions</span><strong>{subs.length}</strong><small>Recorded subscription events</small></div></div><div className="dash-stat"><div className="dash-stat-icon"><Users size={18}/></div><div><span>Active subscriptions</span><strong>{active}</strong><small>Currently active</small></div></div></div><div className="admin-table">{subs.length?subs.map(s=><div className="dash-row" key={s.id}><div className="row-icon"><Receipt size={16}/></div><div><b>{s.subscription_plans?.name||'Plan'}</b><span>User {s.user_id.slice(0,8)} · {s.status}</span></div><div><strong>₹{Number(s.subscription_plans?.monthly_price||0).toLocaleString('en-IN')}</strong><small>{new Date(s.created_at).toLocaleDateString('en-IN')}</small></div></div>):<div className="dash-empty">No subscription history yet.</div>}</div></section>;
 return <section className="admin-analytics"><div className="dash-stats"><div className="dash-stat"><div className="dash-stat-icon"><Users size={18}/></div><div><span>Registered users</span><strong>{users.length}</strong><small>Profiles in RoomOra</small></div></div><div className="dash-stat"><div className="dash-stat-icon"><Wallet size={18}/></div><div><span>Active subscriptions</span><strong>{active}</strong><small>Current status</small></div></div><div className="dash-stat"><div className="dash-stat-icon"><Receipt size={18}/></div><div><span>6-month plan revenue</span><strong>₹{revenue.toLocaleString('en-IN')}</strong><small>Based on recorded plan prices</small></div></div></div><div className="dash-panel"><div className="dash-panel-head"><div><span>LAST 6 MONTHS</span><h3>Subscription activity</h3></div><BarChart3 size={18}/></div><div className="admin-chart">{monthly.map(m=><div className="admin-chart-col" key={m.label}><span>{m.count}</span><div className="admin-bar" style={{height:`${Math.max(8,(m.count/max)*150)}px`}}/><small>{m.label}</small></div>)}</div></div><div className="dash-panel"><div className="dash-panel-head"><div><span>DATA WINDOW</span><h3>What these numbers represent</h3></div><CalendarDays size={18}/></div><p className="modal-copy">Subscription counts and revenue are calculated from recorded subscription events. This admin-only section does not expose these analytics to tenants, owners, or shops.</p></div></section>;
}
