import React, { useState } from 'react';
import { Megaphone, X } from 'lucide-react';
import { supabase } from './lib/supabase';

export default function AdvertisePanel({ onCreated, tokenBalance }) {
  const [open, setOpen] = useState(false), [type, setType] = useState('room'), [title, setTitle] = useState(''), [busy, setBusy] = useState(false), [message, setMessage] = useState('');
  const submit = async e => { e.preventDefault(); setMessage(''); if (tokenBalance < 5) { setMessage('You need at least 5 tokens to advertise.'); return; } setBusy(true); const { error } = await supabase.rpc('create_advertisement', { p_item_type: type, p_title: title.trim() }); if (error) setMessage(error.message || 'Could not create advertisement.'); else { setTitle(''); setOpen(false); onCreated?.(); } setBusy(false); };
  return <><button className="dash-primary" onClick={() => setOpen(true)}><Megaphone size={16}/> Advertise · 5 tokens</button>{open && <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && setOpen(false)}><section className="auth-modal" role="dialog" aria-modal="true"><button className="modal-close" onClick={() => setOpen(false)}><X size={18}/></button><div className="eyebrow"><Megaphone size={14}/> ROOMORA ADVERTISEMENT</div><h2>Advertise your listing.</h2><p className="modal-copy">Each advertisement costs 5 tokens and stays active for one month.</p><form onSubmit={submit}><label className="form-label">What are you advertising?<select value={type} onChange={e => setType(e.target.value)}><option value="room">Room</option><option value="furniture">Furniture</option></select></label><label className="form-label">Advertisement title<input value={title} onChange={e => setTitle(e.target.value)} placeholder="e.g. Furnished room in Gomti Nagar" required maxLength={120}/></label><div className="auth-message">Available tokens: <strong>{tokenBalance}</strong> · Cost: <strong>5</strong></div>{message && <div className="auth-message">{message}</div>}<button className="auth-submit" disabled={busy || tokenBalance < 5}>{busy ? 'Publishing…' : 'Publish advertisement'}</button></form></section></div>}</>;
}
