import React,{useEffect,useMemo,useState} from 'react';
import {Activity,ArrowLeft,BarChart3,Bell,Building2,ChevronRight,Coins,Home,LayoutDashboard,LogOut,Menu,Package,RefreshCw,ShieldCheck,ShoppingBag,Users,Wallet,X} from 'lucide-react';
import {supabase} from './lib/supabase';
import AddRoomPanel from './AddRoomPanel'; import PublishItemPanel from './PublishItemPanel'; import MarketplacePanel from './MarketplacePanel'; import MyListingsPanel from './MyListingsPanel'; import SavedItemsPanel from './SavedItemsPanel'; import SubscriptionManager from './SubscriptionManager'; import AdminAnalytics from './AdminAnalytics'; import DashboardWorkspacePanel from './components/dashboard/DashboardWorkspacePanel';
import './dashboard.css';import './mobile.css';import './marketplace-crud.css';
const nav={admin:[['marketplace','Marketplace',ShoppingBag],['my-listings','My published items',Package],['saved','Saved items',Package],['overview','Overview',LayoutDashboard],['users','Users',Users],['rooms','Rooms',Home],['subscriptions','Subscriptions',Wallet],['analytics','Analytics',BarChart3],['history','Subscription history',Activity],['tokens','Tokens',Coins]],owner:[['marketplace','Marketplace',ShoppingBag],['my-listings','My published items',Package],['saved','Saved items',Package],['overview','Overview',LayoutDashboard],['rooms','My rooms',Home],['activity','My activity',Activity],['inquiries','Inquiries',Bell]],shop:[['marketplace','Marketplace',ShoppingBag],['my-listings','My published items',Package],['saved','Saved items',Package],['overview','Overview',LayoutDashboard],['products','Products',Package],['rooms','Rooms',Home],['activity','My activity',Activity],['orders','Orders',Package]],tenant:[['marketplace','Marketplace',ShoppingBag],['my-listings','My published items',Package],['saved','Saved items',Package],['overview','Overview',LayoutDashboard],['activity','My activity',Activity],['contacts','Contacts',Bell]]};
function Empty({icon:Icon,title,text}){return <div className="dash-empty"><div className="dash-empty-icon"><Icon size={20}/></div><b>{title}</b><span>{text}</span></div>}
export default function Dashboard({user,profile,onSignOut}){
 const admin=profile?.is_admin===true||user?.email?.toLowerCase()==='roomora1910@gmail.com';const role=admin?'admin':profile?.is_shop?'shop':profile?.is_owner?'owner':'tenant';
 const initialView=new URLSearchParams(window.location.search).get('view');const[active,setActive]=useState(()=>nav[role].some(([k])=>k===initialView)?initialView:'marketplace'),[mobileOpen,setMobileOpen]=useState(false),[rooms,setRooms]=useState([]),[plans,setPlans]=useState([]),[tokens,setTokens]=useState(0),[transactions,setTransactions]=useState([]),[count,setCount]=useState(0),[publishOpen,setPublishOpen]=useState(false);
 const refresh=async()=>{const base=[supabase.from('rooms').select('*').order('created_at',{ascending:false}).limit(50),supabase.from('subscription_plans').select('*').order('monthly_price'),supabase.rpc('get_my_token_balance'),supabase.from('token_transactions').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(20)];if(admin)base.push(supabase.from('marketplace_items').select('*',{count:'exact',head:true}).eq('status','published').gt('expires_at',new Date().toISOString()));const[r,p,t,tx,c]=await Promise.all(base);setRooms(r.data||[]);setPlans(p.data||[]);setTokens(Number(t.data||0));setTransactions(tx.data||[]);setCount(c?.count||0)};
 useEffect(()=>{refresh()},[user?.id,admin]);
 useEffect(()=>{const onPop=()=>{const view=new URLSearchParams(window.location.search).get('view');setActive(nav[role].some(([k])=>k===view)?view:'marketplace');setMobileOpen(false)};window.addEventListener('popstate',onPop);return()=>window.removeEventListener('popstate',onPop)},[role]);
 const mine=useMemo(()=>rooms.filter(x=>x.owner_id===user.id),[rooms,user.id]);
 const go=k=>{if(k===active)return;window.history.pushState({dashboardView:k},'',`${window.location.pathname}?view=${encodeURIComponent(k)}`);setActive(k);setMobileOpen(false)};
 const back=()=>window.history.back();
 const title=active==='marketplace'?'RoomOra Marketplace':active==='my-listings'?'My published items':active==='saved'?'Saved items':active==='overview'?'Overview':active==='rooms'?(admin?'Rooms':'My rooms'):active==='activity'?'My activity':active==='users'?'Users':active==='products'?'Products':active==='orders'?'Orders':active==='inquiries'?'Inquiries':active==='contacts'?'Contacts':active==='subscriptions'?'Subscriptions':active==='analytics'?'Analytics':active==='history'?'Subscription history':active==='tokens'?'Tokens':'RoomOra';
 return <div className="dashboard-shell"><aside className={mobileOpen?'dash-sidebar open':'dash-sidebar'}><div className="dash-brand"><span className="brand-mark">R</span><span>Room<span>Ora</span></span><button className="dash-close" onClick={()=>setMobileOpen(false)}><X size={18}/></button></div><div className="dash-profile"><div className="dash-avatar">{(profile?.display_name||user?.email||'R').slice(0,1).toUpperCase()}</div><div><b>{profile?.display_name||'RoomOra user'}</b><span>{admin?'Administrator':role}</span></div></div><nav className="dash-nav">{nav[role].map(([k,label,Icon])=><button key={k} className={active===k?'active':''} onClick={()=>go(k)}><Icon size={17}/><span>{label}</span><ChevronRight size={14}/></button>)}</nav><button className="dash-signout" onClick={onSignOut}><LogOut size={17}/> Sign out</button></aside>{mobileOpen&&<button className="dash-overlay" onClick={()=>setMobileOpen(false)}/>}<main className="dash-main"><header className="dash-top"><div className="dash-top-left"><button className="dash-menu" onClick={()=>setMobileOpen(true)}><Menu size={20}/></button>{active!=='marketplace'&&<button className="dash-back" onClick={back}><ArrowLeft size={18}/> Back</button>}<div><span className="dash-kicker">ROOMORA {role.toUpperCase()}</span><h1>{title}</h1></div></div><div className="dash-top-actions"><button className="dash-icon-btn" title="Refresh dashboard" onClick={refresh}><RefreshCw size={18}/></button><div className="dash-top-user">{profile?.display_name||user?.email}</div></div></header><section className="dash-content">
 {active==='marketplace'&&<MarketplacePanel user={user} profile={profile}/>} {active==='my-listings'&&<MyListingsPanel user={user} onPublish={()=>setPublishOpen(true)}/>} {active==='saved'&&<SavedItemsPanel user={user}/>} {publishOpen&&<PublishItemPanel user={user} tokenBalance={tokens} onCreated={()=>{setPublishOpen(false);refresh()}}/>}
 {active==='overview'&&<section className="dash-panel dash-reveal"><div className="dash-panel-head"><div><span>{admin?'ADMIN':'WORKSPACE'}</span><h3>Overview</h3></div><LayoutDashboard size={18}/></div>{admin?<div className="admin-grid"><div><strong>{count}</strong><span>Published marketplace items</span></div><div><strong>{rooms.length}</strong><span>Room records</span></div><div><strong>{plans.filter(x=>x.active).length}</strong><span>Active plans</span></div></div>:<Empty icon={ShoppingBag} title="Marketplace first" text="Browse the marketplace, manage your listings, or review saved items."/>}</section>}
 {active==='activity'&&<section className="dash-panel dash-reveal"><div className="dash-panel-head"><div><span>PRIVATE TO YOU</span><h3>My activity</h3></div><Activity size={18}/></div><div className="dash-stats"><article className="dash-stat"><div className="dash-stat-icon"><Coins size={18}/></div><div><span>Token balance</span><strong>{tokens}</strong><small>5 tokens / item</small></div></article><article className="dash-stat"><div className="dash-stat-icon"><Home size={18}/></div><div><span>My rooms</span><strong>{mine.length}</strong><small>Your room records</small></div></article></div>{transactions.length?transactions.map(t=><div className="dash-row" key={t.id}><div className="row-icon"><Coins size={16}/></div><div><b>{t.transaction_type}</b><span>{t.description}</span></div><strong>{t.amount>0?'+':''}{t.amount}</strong></div>):<Empty icon={Activity} title="No recent activity" text="Your token activity will appear here."/>}</section>}
 {active==='rooms'&&<section className="dash-panel dash-reveal"><div className="dash-panel-head"><div><span>ROOMS</span><h3>{admin?'All rooms':'My rooms'}</h3></div>{role==='owner'&&<AddRoomPanel user={user} onCreated={refresh}/>}<Home size={18}/></div>{(admin?rooms:mine).length?(admin?rooms:mine).map(r=><div className="dash-row" key={r.id}><div className="row-icon"><Building2 size={16}/></div><div><b>{r.title}</b><span>{r.locality}, {r.city} · {r.status}</span></div><strong>₹{Number(r.monthly_price).toLocaleString('en-IN')}</strong></div>):<Empty icon={Home} title="No rooms yet" text="Room listings will appear here."/>}</section>}
 {['users','products','inquiries','contacts','orders'].includes(active)&&<DashboardWorkspacePanel kind={active} user={user} admin={admin}/>} 
 {active==='subscriptions'&&admin&&<section className="dash-panel"><div className="dash-panel-head"><div><span>ADMIN</span><h3>Subscriptions</h3></div><Wallet size={18}/></div><SubscriptionManager plans={plans.filter(x=>['basic','premium'].includes(x.name.toLowerCase()))} onUpdated={refresh}/></section>}{active==='analytics'&&admin&&<AdminAnalytics/>}{active==='history'&&admin&&<AdminAnalytics historyOnly/>}{active==='tokens'&&admin&&<section className="dash-panel"><div className="dash-panel-head"><div><span>ADMIN</span><h3>Token activity</h3></div><Coins size={18}/></div>{transactions.map(t=><div className="dash-row" key={t.id}><div><b>{t.transaction_type}</b><span>{t.description}</span></div><strong>{t.amount}</strong></div>)}</section>}
 </section></main></div>
}
