import React,{useEffect,useMemo,useState} from 'react';
import {createPortal} from 'react-dom';
import {ShoppingBag,Bookmark,X,MapPin,Phone,UserRound,Pencil,Trash2,Send} from 'lucide-react';
import {supabase} from './lib/supabase';
import MarketplaceToolbar from './components/marketplace/MarketplaceToolbar';
import MarketplaceRows from './components/marketplace/MarketplaceRows';
import MarketplaceGallery from './components/marketplace/MarketplaceGallery';
import './marketplace.css';
import './marketplace-crud.css';

const rows=[['room','Rooms'],['furniture','Furniture'],['stationery','Stationery'],['second_hand','Other second-hand items']];
const fallback={room:'https://images.unsplash.com/photo-1560185008-b033106af5c3?auto=format&fit=crop&w=900&q=85',furniture:'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=85',stationery:'https://images.unsplash.com/photo-1456735190827-d1262f71b8a3?auto=format&fit=crop&w=900&q=85',second_hand:'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=900&q=85'};
const catLabel=c=>rows.find(x=>x[0]===c)?.[1]||'Marketplace item';

export default function MarketplacePanel({user,profile}){
 const [items,setItems]=useState([]),[profiles,setProfiles]=useState({}),[q,setQ]=useState(''),[category,setCategory]=useState('all'),[selected,setSelected]=useState(null),[saved,setSaved]=useState([]),[loading,setLoading]=useState(true),[chat,setChat]=useState(''),[message,setMessage]=useState(''),[notice,setNotice]=useState(''),[edit,setEdit]=useState(null),[savingEdit,setSavingEdit]=useState(false);
 const load=async()=>{if(!supabase||!user)return;setLoading(true);const [pub,own,fav]=await Promise.all([supabase.from('marketplace_items').select('*').eq('status','published').gt('expires_at',new Date().toISOString()).order('published_at',{ascending:false}),supabase.from('marketplace_items').select('*').eq('user_id',user.id).order('created_at',{ascending:false}),supabase.from('marketplace_favorites').select('item_id').eq('user_id',user.id)]);const map=new Map();[...(pub.data||[]),...(own.data||[])].forEach(x=>map.set(x.id,x));const list=[...map.values()];setItems(list);setSaved((fav.data||[]).map(x=>x.item_id));const ids=[...new Set(list.map(x=>x.user_id).filter(Boolean))];if(ids.length){const {data:p}=await supabase.from('profiles').select('id,display_name,phone,contact_email,contact_phone,contact_address').in('id',ids);setProfiles(Object.fromEntries((p||[]).map(x=>[x.id,x])))}setLoading(false)};
 useEffect(()=>{load()},[user?.id]);
 const toggleSave=async id=>{if(!user)return;setNotice('');const isSaved=saved.includes(id);setSaved(v=>isSaved?v.filter(x=>x!==id):[...v,id]);const result=isSaved?await supabase.from('marketplace_favorites').delete().eq('user_id',user.id).eq('item_id',id):await supabase.from('marketplace_favorites').insert({user_id:user.id,item_id:id});if(result.error){setSaved(v=>isSaved?[...v,id]:v.filter(x=>x!==id));setNotice(result.error.message)}};
 const matches=i=>`${i.title||''} ${i.description||''} ${i.locality||''} ${i.city||''}`.toLowerCase().includes(q.trim().toLowerCase());
 const imageFor=(i,c)=>i.image_url||i.image_urls?.[0]||i.image||fallback[c];
 const grouped=useMemo(()=>Object.fromEntries(rows.map(([c])=>[c,items.filter(i=>(category==='all'||category===c||(category==='second_hand'&&['second_hand','other'].includes(i.category)))&&(c==='second_hand'?['second_hand','other'].includes(i.category):i.category===c)&&matches(i))])),[items,q,category]);
 const sendInquiry=async()=>{if(!selected||!message.trim())return;const {error}=await supabase.rpc('create_marketplace_inquiry',{p_item_id:selected.id,p_message:message.trim()});if(error){setNotice(error.message);return}setChat(`Your message was sent to ${profiles[selected.user_id]?.display_name||'the publisher'}.`);setMessage('');};
 const deleteItem=async item=>{if(!window.confirm(`Delete “${item.title}”? This cannot be undone.`))return;const {error}=await supabase.from('marketplace_items').delete().eq('id',item.id).eq('user_id',user.id);if(error){setNotice(error.message);return}setSelected(null);setNotice('Listing deleted.');await load()};
 const saveEdit=async()=>{if(!edit)return;setSavingEdit(true);const {data,error}=await supabase.from('marketplace_items').update({title:edit.title.trim(),description:edit.description.trim(),price:Number(edit.price)||0,city:edit.city.trim(),locality:edit.locality.trim(),category:edit.category}).eq('id',edit.id).eq('user_id',user.id).select().single();setSavingEdit(false);if(error){setNotice(error.message);return}setEdit(null);setSelected(data);setNotice('Listing updated.');await load()};
 const toolbar=<MarketplaceToolbar query={q} onQueryChange={setQ} category={category} onCategoryChange={setCategory} categories={rows}/>;
 return <section className="marketplace-panel">
  {typeof document!=='undefined'&&document.getElementById('dash-market-tools')&&createPortal(toolbar,document.getElementById('dash-market-tools'))}
  {notice&&<div className="auth-message">{notice}</div>}
  {loading?<div className="dash-empty">Loading marketplace…</div>:<MarketplaceRows rows={rows} grouped={grouped} user={user} saved={saved} onSelect={setSelected} onSave={toggleSave} onEdit={setEdit} onDelete={deleteItem} imageFor={imageFor}/>} 
  {selected&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><section className="auth-modal marketplace-detail-modal"><button className="modal-close" onClick={()=>setSelected(null)}><X size={18}/></button><MarketplaceGallery item={selected}/><span className="market-detail-category">{catLabel(selected.category)} {selected.user_id===user?.id?' · Your listing':''}</span><h2>{selected.title}</h2><p>{selected.description}</p><strong className="market-modal-price">₹{Number(selected.price||0).toLocaleString('en-IN')}</strong><p><MapPin size={14}/> {selected.locality}, {selected.city}</p><div className="publisher-box"><div className="row-icon"><UserRound size={18}/></div><div><b>{profiles[selected.user_id]?.display_name||'Publisher'}</b><span>{selected.user_id===user?.id?'This is your listing.':(profiles[selected.user_id]?.contact_phone||profiles[selected.user_id]?.phone||profiles[selected.user_id]?.contact_email||'Publisher contact is available after sending an inquiry.')}</span></div></div>{selected.user_id===user?.id?<div className="dash-action-row"><button className="dash-primary" onClick={()=>setEdit({...selected})}><Pencil size={16}/> Edit listing</button><button className="outline-btn" onClick={()=>deleteItem(selected)}><Trash2 size={16}/> Delete listing</button></div>:<><textarea className="form-input" value={message} onChange={e=>setMessage(e.target.value)} placeholder="Write a message to the publisher…" rows="4" maxLength={1000}/><div className="dash-action-row"><button className="dash-primary" onClick={sendInquiry} disabled={!message.trim()}><Send size={16}/> Send inquiry</button><button className="outline-btn" onClick={()=>toggleSave(selected.id)}><Bookmark size={16}/> {saved.includes(selected.id)?'Saved':'Save item'}</button></div></>}{chat&&<div className="auth-message"><Phone size={14}/> {chat}</div>}</section></div>}
  {edit&&<div className="modal-backdrop"><section className="auth-modal"><button className="modal-close" onClick={()=>setEdit(null)}><X size={18}/></button><div className="eyebrow"><Pencil size={14}/> EDIT LISTING</div><h2>Update your listing.</h2><p className="modal-copy">Editing keeps the existing publication and images intact.</p><label className="form-label">Category<select value={edit.category} onChange={e=>setEdit(x=>({...x,category:e.target.value}))}>{[['room','Room'],['furniture','Furniture'],['second_hand','Second-hand item'],['stationery','Stationery'],['other','Other']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="form-label">Title<input value={edit.title} maxLength={120} onChange={e=>setEdit(x=>({...x,title:e.target.value}))}/></label><label className="form-label">Description<textarea value={edit.description} rows="4" onChange={e=>setEdit(x=>({...x,description:e.target.value}))}/></label><div className="role-grid"><label className="form-label">Price (₹)<input type="number" min="0" value={edit.price} onChange={e=>setEdit(x=>({...x,price:e.target.value}))}/></label><label className="form-label">Locality<input value={edit.locality} onChange={e=>setEdit(x=>({...x,locality:e.target.value}))}/></label></div><label className="form-label">City<input value={edit.city} onChange={e=>setEdit(x=>({...x,city:e.target.value}))}/></label><div className="dash-action-row"><button className="auth-submit" onClick={saveEdit} disabled={savingEdit}>{savingEdit?'Saving…':'Save changes'}</button><button className="outline-btn" onClick={()=>setEdit(null)}>Cancel</button></div></section></div>}
 </section>;
}
