import React,{useEffect,useMemo} from 'react';
import {ArrowRight,ShoppingBag} from 'lucide-react';
import {animate,stagger} from 'animejs';
import MarketplaceCard from './components/marketplace/MarketplaceCard';
import MarketplaceFilters from './components/marketplace/MarketplaceFilters';
import {MARKETPLACE_CATEGORIES,groupMarketplaceItems} from './components/marketplace/marketplace';
import useMarketplaceItems from './hooks/useMarketplaceItems';
import './marketplace.css';
export default function MarketplaceLanding({onOpenAuth}){const{items}=useMarketplaceItems(null);const[filter,setFilter]=React.useState('all');const grouped=useMemo(()=>groupMarketplaceItems(items,filter),[items,filter]);const counts=useMemo(()=>Object.fromEntries(MARKETPLACE_CATEGORIES.map(([c])=>[c,groupMarketplaceItems(items,c)[c].length])),[items]);const visible=MARKETPLACE_CATEGORIES.filter(([c])=>grouped[c]?.length>0);useEffect(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;animate('.market-landing-row',{opacity:[0,1],translateY:[14,0],delay:stagger(70),duration:500,ease:'out(3)'})},[items.length,filter]);return <section className="market-landing" id="marketplace"><div className="market-landing-head"><div><div className="eyebrow"><ShoppingBag size={14}/> ROOMORA MARKETPLACE</div><h2>Browse by category.</h2><p>Fresh published listings appear here automatically. Sign in for full details.</p></div><button className="outline-btn" onClick={onOpenAuth}>Sign in to view details <ArrowRight size={16}/></button></div><MarketplaceFilters value={filter} onChange={setFilter} counts={counts} className="landing-filters"/>{visible.length?<div className="market-landing-rows">{visible.map(([category,label])=>{const list=grouped[category]||[];return <div className="market-landing-row" key={category}><div className="market-row-title"><h3>{label}</h3><span className="market-row-count">{list.length} available</span></div><div className="market-horizontal" role="region" aria-label={`${label} listings`}>{list.map(item=><MarketplaceCard key={item.id} item={item} onOpen={onOpenAuth}/>)}</div></div>})}</div>:<div className="landing-no-results"><ShoppingBag size={20}/><b>No {filter==='all'?'marketplace items':MARKETPLACE_CATEGORIES.find(x=>x[0]===filter)?.[1].toLowerCase()} available right now.</b><span>Try another category.</span></div>}</section>}
