import React,{useEffect,useMemo,useState} from 'react';
import {Search,ShoppingBag,Bookmark,MessageCircle,X,MapPin,Phone,UserRound} from 'lucide-react';
import {supabase} from './lib/supabase';
import './marketplace.css';
const rows=[['room','Rooms'],['furniture','Furniture'],['stationery','Stationery'],['second_hand','Other second-hand items']];
const fallback={room:'https://images.unsplash.com/photo-1560185008-b033106af5c3?auto=format&fit=crop&w=900&q=85',furniture:'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=85',stationery:'https://images.unsplash.com/photo-1456735190827-d1262f71b8a3?auto=format&fit=crop&w=900&q=85',second_hand:'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=900&q=85'};
export default function MarketplacePanel(){
 const [items,setItems]=useState([]),[profiles,setProfiles]=useState({}),[q,setQ]=useState(''),[selected,setSelected]=useState(null),[saved,setSaved]=useState(()=>JSON.parse(localStorage.getItem('roomora-saved-items')||'[]')),[loading,setLoading]=useState(true),[chat,setChat]=useState('');
 useEffect(()=>{let live=true;(async()=>{if(!supabase)return;setLoading(true);const {data}=await supabase.from('marketplace_items').select('*').eq('status','published').gt('expires_at',new Date().toISOString()).order('published_at',{ascending:false});if(!live)return;const list=data||[];setItems(list);const ids=[...new Set(list.map(x=>x.user_id).filter(Boolean))];if(ids.length){const {data:p}=await supabase.from('profiles').select('id,display_name,phone').in('id',ids);setProfiles(Object.fromEntries((p||[]).map(x=>[x.id,x])))}setLoading(false)})();return()=>{live=false}},[]);
 const toggleSave=id=>{const next=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];setSaved(next);localStorage.setItem('roomora-saved-items',JSON.stringify(next))};
 const matches=i=>`${i.title||''} ${i.description||''} ${i.locality||''} ${i.city||''}`.toLowerCase().includes(q.toLowerCase());
 const imageFor=(i,c)=>i.image_url||i.image||fallback[c];
 const grouped=useMemo(()=>Object.fromEntries(rows.map(([c])=>[c,items.filter(i=>(c==='second_hand'?['second_hand','other'].includes(i.category):i.category===c)&&matches(i))])),[items,q]);
 const openChat=i=>{setChat(`You can contact ${profiles[i.user_id]?.display_name||'the publisher'} about “${i.title}”.`);setSelected(i)};
 return <section className="marketplace-panel"><div className="market-head"><div><span className="dash-kicker">ROOMORA MARKETPLACE</span><h2>Browse, save and connect.</h2><p>Choose any published item to see its complete details and publisher information.</p></div><ShoppingBag size={22}/></div><div className="market-tools"><div className="market-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search rooms, furniture, stationery…"/></div></div>{loading?<div className="dash-empty">Loading marketplace…</div>:<div className="market-landing-rows">{rows.map(([category,label])=>{const list=grouped[category]||[];return <div className="market-landing-row" key={category} style={{opacity:1}}><div className="market-row-title"><h3>{label}</h3><span className="market-row-count">{list.length} available</span></div>{list.length?<div className="market-horizontal">{list.map(item=><article className="market-detail-card" key={item.id}><button className="market-detail-image" onClick={()=>setSelected(item)}><img src={imageFor(item,category)} alt="" loading="lazy"/></button><div className="market-detail-body"><span className="market-detail-category">{label}</span><h4>{item.title}</h4><p>{item.description}</p><strong>₹{Number(item.price||0).toLocaleString('en-IN')}</strong><small><MapPin size={12}/> {item.locality}, {item.city}</small><footer><span>Available until {new Date(item.expires_at).toLocaleDateString()}</span><button className={saved.includes(item.id)?'market-save saved':'market-save'} onClick={()=>toggleSave(item.id)}><Bookmark size={15}/> {saved.includes(item.id)?'Saved':'Save'}</button></footer></div></article>)}</div>:<div className="dash-empty"><div className="dash-empty-icon"><ShoppingBag size={20}/></div><b>No {label.toLowerCase()} available</b><span>Published items will appear here until they expire.</span></div>}</div>})}</div>}
 {selected&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><section className="auth-modal marketplace-detail-modal"><button className="modal-close" onClick={()=>setSelected(null)}><X size={18}/></button><img className="market-modal-image" src={imageFor(selected,selected.category==='second_hand'?'second_hand':selected.category)} alt=""/><span className="market-detail-category">{rows.find(x=>x[0]===selected.category)?.[1]||'Marketplace item'}</span><h2>{selected.title}</h2><p>{selected.description}</p><strong className="market-modal-price">₹{Number(selected.price||0).toLocaleString('en-IN')}</strong><p><MapPin size={14}/> {selected.locality}, {selected.city}</p><div className="publisher-box"><div className="row-icon"><UserRound size={18}/></div><div><b>{profiles[selected.user_id]?.display_name||'Publisher'}</b><span>{profiles[selected.user_id]?.phone||'Publisher contact is available here.'}</span></div></div><div className="dash-action-row"><button className="dash-primary" onClick={()=>toggleSave(selected.id)}><Bookmark size={16}/> {saved.includes(selected.id)?'Saved':'Save item'}</button><button className="outline-btn" onClick={()=>openChat(selected)}><MessageCircle size={16}/> Chat with publisher</button></div>{chat&&<div className="auth-message"><Phone size={14}/> {chat}</div>}</section></div>}
 </section>
}
