import React,{useEffect,useState} from 'react';
import {Pencil,Trash2,Plus,Package,MapPin,Clock} from 'lucide-react';
import {supabase} from './lib/supabase';
const cats=[['room','Room'],['furniture','Furniture'],['second_hand','Second-hand item'],['stationery','Stationery'],['other','Other']];
export default function MyListingsPanel({user,onPublish}){
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[edit,setEdit]=useState(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const load=async()=>{setLoading(true);const {data,error}=await supabase.from('marketplace_items').select('*').eq('user_id',user.id).order('created_at',{ascending:false});if(error)setNotice(error.message);setItems(data||[]);setLoading(false)};
 useEffect(()=>{load()},[user?.id]);
 const save=async()=>{if(!edit)return;setBusy(true);setNotice('');const {data,error}=await supabase.from('marketplace_items').update({category:edit.category,title:edit.title.trim(),description:(edit.description||'').trim(),price:Number(edit.price)||0,locality:(edit.locality||'').trim(),city:(edit.city||'').trim()}).eq('id',edit.id).eq('user_id',user.id).select().single();setBusy(false);if(error){setNotice(error.message);return}setEdit(null);setItems(v=>v.map(x=>x.id===data.id?data:x));setNotice('Listing updated.');};
 const remove=async item=>{if(!window.confirm(`Delete “${item.title}”? This cannot be undone.`))return;const {error}=await supabase.from('marketplace_items').delete().eq('id',item.id).eq('user_id',user.id);if(error){setNotice(error.message);return}setItems(v=>v.filter(x=>x.id!==item.id));setNotice('Listing deleted.');};
 return <section className="dash-panel dash-reveal"><div className="dash-panel-head"><div><span>MY MARKETPLACE</span><h3>My published items</h3></div><button className="dash-primary" onClick={onPublish}><Plus size={16}/> Publish new item</button></div><p className="panel-subcopy">Manage your own listings here. Saving listings stays in Marketplace.</p>{notice&&<div className="auth-message">{notice}</div>}{loading?<div className="dash-empty">Loading your listings…</div>:items.length?<div className="my-listings-grid">{items.map(item=><article className="my-listing-card" key={item.id}><img src={item.image_url} alt={item.title}/><div className="my-listing-body"><span className={`listing-status ${item.status}`}>{item.status}</span><h4>{item.title}</h4><p>{item.description}</p><strong>₹{Number(item.price||0).toLocaleString('en-IN')}</strong><small><MapPin size={12}/> {item.locality}, {item.city}</small><small><Clock size={12}/> {item.expires_at?`Expires ${new Date(item.expires_at).toLocaleDateString()}`:'No expiry'}</small><div className="my-listing-actions"><button className="outline-btn" onClick={()=>setEdit({...item})}><Pencil size={14}/> Edit</button><button className="outline-btn danger-btn" onClick={()=>remove(item)}><Trash2 size={14}/> Delete</button></div></div></article>)}</div>:<div className="dash-empty"><div className="dash-empty-icon"><Package size={20}/></div><b>No published items yet</b><span>Publish your first room, furniture or second-hand item.</span><button className="dash-primary" onClick={onPublish}><Plus size={16}/> Publish item</button></div>}
 {edit&&<div className="modal-backdrop"><section className="auth-modal"><button className="modal-close" onClick={()=>setEdit(null)}>×</button><div className="eyebrow"><Pencil size={14}/> EDIT LISTING</div><h2>Update your item.</h2><label className="form-label">Category<select value={edit.category} onChange={e=>setEdit(x=>({...x,category:e.target.value}))}>{cats.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label className="form-label">Title<input value={edit.title} onChange={e=>setEdit(x=>({...x,title:e.target.value}))} maxLength={120}/></label><label className="form-label">Description<textarea value={edit.description||''} rows="4" onChange={e=>setEdit(x=>({...x,description:e.target.value}))}/></label><div className="role-grid"><label className="form-label">Price (₹)<input type="number" min="0" value={edit.price||0} onChange={e=>setEdit(x=>({...x,price:e.target.value}))}/></label><label className="form-label">Locality<input value={edit.locality||''} onChange={e=>setEdit(x=>({...x,locality:e.target.value}))}/></label></div><label className="form-label">City<input value={edit.city||''} onChange={e=>setEdit(x=>({...x,city:e.target.value}))}/></label><div className="dash-action-row"><button className="auth-submit" onClick={save} disabled={busy}>{busy?'Saving…':'Save changes'}</button><button className="outline-btn" onClick={()=>setEdit(null)}>Cancel</button></div></section></div>}
 </section>;
}
