import React,{useState} from 'react';
import {Package,Upload,X,Image as ImageIcon} from 'lucide-react';
import {supabase} from './lib/supabase';
const cats=[['room','Room'],['furniture','Furniture'],['second_hand','Second-hand item'],['stationery','Stationery'],['other','Other']];
const initial={category:'room',title:'',description:'',price:'',city:'Lucknow',locality:'',images:[]};
export default function PublishItemPanel({user,tokenBalance,onCreated}){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[f,setF]=useState(initial);
 const c=e=>setF(x=>({...x,[e.target.name]:e.target.value}));
 const files=e=>{const selected=Array.from(e.target.files||[]).slice(0,3);setF(x=>({...x,images:selected}));setMsg(e.target.files?.length>3?'Only the first 3 images can be selected.':'')};
 const remove=i=>setF(x=>({...x,images:x.images.filter((_,n)=>n!==i)}));
 const submit=async e=>{e.preventDefault();setMsg('');if(f.images.length<1){setMsg('Please upload at least 1 image.');return}if(f.images.length>3){setMsg('You can upload a maximum of 3 images.');return}if(tokenBalance<5){setMsg('You need 5 tokens to publish an item.');return}setBusy(true);try{const urls=[];for(const image of f.images){const ext=image.name.split('.').pop().toLowerCase();const path=`${user.id}/${crypto.randomUUID()}.${ext}`;const upload=await supabase.storage.from('marketplace-images').upload(path,image,{upsert:false,contentType:image.type});if(upload.error)throw upload.error;const {data:urlData}=supabase.storage.from('marketplace-images').getPublicUrl(path);urls.push(urlData.publicUrl)}const {data,error}=await supabase.rpc('publish_item',{p_category:f.category,p_title:f.title.trim(),p_description:f.description.trim(),p_price:Number(f.price)||0,p_image_url:urls[0],p_image_urls:urls,p_city:f.city.trim(),p_locality:f.locality.trim()});if(error)throw error;setOpen(false);setF(initial);onCreated?.(data)}catch(error){setMsg(error.message||'Unable to publish this item.')}finally{setBusy(false)}};
 return <><button className="dash-primary" onClick={()=>setOpen(true)}><Upload size={16}/> Publish item · 5 tokens</button>{open&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><section className="auth-modal"><button className="modal-close" onClick={()=>setOpen(false)}><X size={18}/></button><div className="eyebrow"><Package size={14}/> ROOMORA MARKETPLACE</div><h2>Publish an item.</h2><p className="modal-copy">Choose a category and upload 1 to 3 images. Publishing costs 5 tokens and keeps the item visible for one month.</p><form onSubmit={submit}><label className="form-label">Category<select name="category" value={f.category} onChange={c}>{cats.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label className="form-label">Product / room images <span aria-hidden="true">*</span><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={files} required/><small>Choose 1 to 3 JPG, PNG or WebP images.</small></label>{f.images.length>0&&<div className="upload-previews">{f.images.map((img,i)=><div className="upload-preview" key={`${img.name}-${i}`}><img src={URL.createObjectURL(img)} alt={`Selected image ${i+1}`}/><button type="button" onClick={()=>remove(i)} aria-label={`Remove image ${i+1}`}><X size={14}/></button><span>{i+1}</span></div>)}</div>}<label className="form-label">Title<input name="title" value={f.title} onChange={c} placeholder="What are you offering?" required maxLength={120}/></label><label className="form-label">Description<textarea name="description" value={f.description} onChange={c} placeholder="Add useful details" rows="4" required/></label><div className="role-grid"><label className="form-label">Price (₹)<input name="price" type="number" min="0" value={f.price} onChange={c} placeholder="500"/></label><label className="form-label">Locality<input name="locality" value={f.locality} onChange={c} placeholder="Gomti Nagar" required/></label></div><label className="form-label">City<input name="city" value={f.city} onChange={c} required/></label><div className="auth-message">Images: <strong>{f.images.length}/3</strong> · Available: <strong>{tokenBalance}</strong> tokens · Publishing: <strong>5</strong> tokens</div>{msg&&<div className="auth-message">{msg}</div>}<button className="auth-submit" disabled={busy||tokenBalance<5}>{busy?'Publishing…':'Publish for 5 tokens'}</button></form></section></div>}</>}
